### ISSUE TITLE
آمار بازدید کنندگان

### ISSUE THREAD

**Issue by khajavi** [shomabegoo/shomabegoo#2]
<div dir=rtl>
در حال حاضر هیچ حسی نسبت به تعداد بازدیدکنندگان، نحوهٔ ورودشان به وب‌گاه و غیره نداریم.

**Comment by sinoohe** [comment]
میتونیم از گوگل آنالیتیکز استفاده کنیم.

**Comment by khajavi** [comment]
موافقم،

پیشنهادم اینه که قبلش یه جست-و-جو بزنیم، اولویّت استفاده از نرم‌افزارهای
آزاد هست.

On Tue, Mar 22, 2016 at 4:03 PM, Mehran khajavi <notifications@github.com>
wrote:

> میتونیم از گوگل آنالیتیکز استفاده کنیم.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/shomabegoo/shomabegoo/issues/2#issuecomment-199772173>
>



-- 
﻿﻿Milād Khājavi
http://blog.khajavi.ir
Having the source means you can do it yourself.
I tried to change the world, but I couldn’t find the source code.

**Comment by sinoohe** [comment]
گوگل آنالیتیکز رو با هیچی نمیتونی مقایسه کنی از لحاظ امکانات

piwik
هم بد نیست اوپن سورسه

**Comment by khajavi** [comment]
همم با توجه به اینکه piwik تعداد استارهاش توی گیت‌هاب بالاس به نظرم میشه
بهش اعتماد کرد. راستی براش کوئیک استارت اپن‌شیفت نوشته‌اند راحت می‌شه اونو
روی اپن‌شیفت بیاریم بالا.
https://github.com/openshift/piwik-openshift-quickstart

On Tue, Mar 22, 2016 at 4:11 PM, Mehran khajavi <notifications@github.com>
wrote:

> گوگل آنالیتیکز رو با هیچی نمیتونی مقایسه کنی از لحاظ امکانات
>
> piwik
> هم بد نیست اوپن سورسه
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/shomabegoo/shomabegoo/issues/2#issuecomment-199774983>
>



-- 
﻿﻿Milād Khājavi
http://blog.khajavi.ir
Having the source means you can do it yourself.
I tried to change the world, but I couldn’t find the source code.

**Comment by sinoohe** [comment]
بسیار خوب

**Comment by khajavi** [comment]
اینم یه روش با heroku و داکر. https://github.com/dz0ny/heroku-docker-piwik
اگه دیدی خیلی زمان‌بره و به صرفه‌نیست می‌تونیم موقتاً از گوگل استفاده کنیم
بعداً سر فرصت از راه‌حل آزاد استفاده کنیم.

On Tue, Mar 22, 2016 at 4:39 PM, Mehran khajavi <notifications@github.com>
wrote:

> بسیار خوب
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/shomabegoo/shomabegoo/issues/2#issuecomment-199782961>
>



-- 
﻿﻿Milād Khājavi
http://blog.khajavi.ir
Having the source means you can do it yourself.
I tried to change the world, but I couldn’t find the source code.
