### ISSUE TITLE
نوشتن داکرفایل برای استقرار آسان

### ISSUE THREAD

**Issue by khajavi** [shomabegoo/shomabegoo#3]

**Comment by sinoohe** [comment]
یه روش آسان اینه فایل 
deb 
بیلد کنیم لوکال و راحت اونو نصب کنیم
اینطوری لوکال هم میتونیم تست کنیم

**Comment by khajavi** [comment]
سلام،
من فعلاً این داکرفایل رو آماده کردم:
https://github.com/shomabegoo/shomabegoo-docker

اگه روزی لازم شد بستهٔ debش رو هم درست می‌کنیم.
