### ISSUE TITLE
باگ ورود به سیستم

### ISSUE THREAD

**Issue by khajavi** [shomabegoo/shomabegoo#6]
<div dir=rtl>
وقتی لاگین نیستیم، و  وارد صفحهٔ یکی از سؤال‌ها می‌شویم، سیستم از ما می‌خواهد که برای پاسخ دادن به آن سؤال لاگین کنیم. اما پس از لاگین، دوباره به همان سؤال برنمی‌گردیم بلکه چنین خطایی ظاهر می‌شود:

![image](https://cloud.githubusercontent.com/assets/235974/13975673/7f3df3f6-f0d5-11e5-8473-c5a057c9e605.png)

**Comment by khajavi** [comment]
<div dir=rtl>
ماموت بین دامنهٔ localhost با 127.0.0.1 فرق می‌گذارد.
یا بین دامنهٔ http://www.shomabegoo.com با http://shomabegoo.com فرق می‌گذارد.

**Comment by sinoohe** [comment]
کجا فرق میگذارد؟

**Comment by khajavi** [comment]
این ایشو تقریباً حل شده‌ست.
فعلاً اولویّتش پایینه. اول یه داکرفایل بسازیم که نرم‌افزار رو تو حالت
پروداکشن تست کنیم. این مشکل اونجا باید تو محیط واقعی خودشو نشون بده.

On Wed, Mar 23, 2016 at 3:26 PM, Mehran khajavi <notifications@github.com>
wrote:

> کجا فرق میگذارد؟
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/shomabegoo/shomabegoo/issues/6#issuecomment-200295507>
>



-- 
﻿﻿Milād Khājavi
http://blog.khajavi.ir
Having the source means you can do it yourself.
I tried to change the world, but I couldn’t find the source code.

**Comment by khajavi** [comment]
<div dir=rtl>
این مشکل هم با قرار دادن این دو خط به پروندهٔ environment.properties حل شد.

```
host=http://shomabegoo.com
home.url=/
```
